### ISSUE TITLE
ENOENT: no such file or directory *.mxl

### ISSUE THREAD

**Issue by hanw-dev** [amcolash/flowkey-scraper#1]
I am getting error on larger sheet music, for example the advanced Canon in D sheet music produces the following error:

```
2021-06-28 15:27:44,158 WARN [<song name>]            SheetStub.java:344  | Too large image: 23,083,200 pixels (vs 20,000,000 max)

...

ENOENT: no such file or directory, open '~/Library/Application Support/flowkey-scraper/tmp/<song name>/<song name>.mxl'
```

full error log: https://pastebin.com/6MmLUJy7

**Comment by amcolash** [comment]
Ah yes, I was also getting this issue on some of the music I was trying. I forgot to finish up that work till now but should be set in the v0.11.0 release I just published. If not, please re-open. I just tried the song on advanced and it worked fine for me!
